### ISSUE TITLE
JSON doesn't prettyprint

### ISSUE THREAD

**Issue by milo526** [CWMCDev/Barend#3]
When accessing any endpoint the returned JSON is not pretty printed.

**Comment by casdr** [comment]
So? Who cares
- Cas de Reuver

Website: http://0fi.net
LinkedIn: https://nl.linkedin.com/in/casdr
Twitter: https://twitter.com/cdr_t
Facebook: https://fb.com/casdereuver
GitHub: http://github.com/casdr
Phone: +31632140979

**Comment by milo526** [comment]
Responses are written using `echo json_encode($data, JSON_PRETTY_PRINT);`
API is showing unexpected behavior

**Comment by casdr** [comment]
Please try to view the page source
- Cas de Reuver

Website: http://0fi.net
LinkedIn: https://nl.linkedin.com/in/casdr
Twitter: https://twitter.com/cdr_t
Facebook: https://fb.com/casdereuver
GitHub: http://github.com/casdr
Phone: +31632140979

**Comment by milo526** [comment]
JSON did indeed pretty print in page source.
Re-open if ability to pretty print in browser.

**Comment by casdr** [comment]
No, that'll require html (pre tag)
