### ISSUE TITLE
Returning empty array when results not cached.

### ISSUE THREAD

**Issue by milo526** [CWMCDev/Barend#4]
When accessing `portal` endpoints the API will return an empty array if the results are not currently cached.
Refreshing the page results in the expected output.

**Comment by casdr** [comment]
Is the script loading the full page with an embedded widget of the grades?

**Comment by casdr** [comment]
Please post a screenshot with the page contents that's being loaded

**Comment by milo526** [comment]
<img width="776" alt="schermafbeelding 2015-12-04 om 15 20 05" src="https://cloud.githubusercontent.com/assets/5261909/11591754/8b25964c-9a9a-11e5-951f-3cf9c0915993.png">
<img width="1110" alt="schermafbeelding 2015-12-04 om 15 20 36" src="https://cloud.githubusercontent.com/assets/5261909/11591774/9cf19da8-9a9a-11e5-9f8b-f79a4f180dc8.png">

**Comment by casdr** [comment]
Is this a screenshot of the FULL page? Or a screenshot of the embedded widget?

**Comment by milo526** [comment]
Previous screenshot was of embedded widget.

Newly supplied screenshot is of the full page.
<img width="1440" alt="schermafbeelding 2015-12-04 om 16 45 10" src="https://cloud.githubusercontent.com/assets/5261909/11593776/6d359b08-9aa6-11e5-9fbf-7a35b38693a5.png">

**Comment by casdr** [comment]
Use the URL of the widget itself, it might be fixed then.

**Comment by milo526** [comment]
Currently used url

```
https://leerlingen.candea.nl/Portaal/Cijferlijst/Examendossier/Cijferlijst?wis_ajax&ajax_object=727&periode727=1
```

Result: 
<img width="1440" alt="schermafbeelding 2015-12-04 om 16 49 34" src="https://cloud.githubusercontent.com/assets/5261909/11593881/0d6db092-9aa7-11e5-841a-ab44b2cea0bf.png">

**Comment by casdr** [comment]
:D

**Comment by milo526** [comment]
Bug not fixed. Caching is still an problem.
URL was used in previous and current endpoint

**Comment by casdr** [comment]
Try to curl the page 2 times
