### ISSUE TITLE
API Endpoint change

### ISSUE THREAD

**Issue by milo526** [CWMCDev/Barend#6]
Do we want API endpoints to change in regards to the schedule?

Problem:
404 when not sending Username and Password for portal

Fix:
Multiple endpoints. One with presention and one without.
Single endpoint, optional presention. Only parse presention if a (correct) username and password has been set.

**Comment by casdr** [comment]
http://racksburg.com/choosing-an-http-status-code/

**Comment by casdr** [comment]
> Do we want API endpoints to change in regards to the schedule?

yes. http://0fi.net/stuff/?dir=http_status
